Finish mobile version project
vvoo21/Portfolio pull request #2
Opened 2022-08-20 11:18 UTC by vvoo21

Hi,
In this pull request, I created a new branch,  the "Works" section whit its cards and the "About myself" section. I used the properties of  CSS Grid and Flexbox. 

I made all this followed the instructions of Portfolio: finish the mobile version project:

-Make sure the content of the "About myself" section is aligned with flexbox.

-In order to lay out the elements in the "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

-Please use ul and li for categories in the "Work" section. Html, css, and Javascript should be list items.

-Please use ul and li for categories in the "About myself" section. Languages, Frameworks, and Skills should be list items.

-You don't need to implement the detail modal window that requires JavaScript.

-You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

-Implement the button interactions (enable, hover, etc.).

Thanks!

2022-08-20 12:01 UTC, Kamba56 commented
Hi @vvoo21 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that not all linters checks are passing. Please kindly fix all linters errors before asking for a code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-20 18:46 UTC, vvoo21 commented
Hi @Kamba56, I fix all the linters errors. Sorry for having asked for a code review before. I hope this time I got all the requirements correct for the code review.

2022-08-20 19:16 UTC, Kamba56 requested changes
Hello @vvoo21, 

You have done a really great job. Your work is one of the best I have seen. Please keep up the good work and you will be a great developer. However, there are a few adjustments you could make.

## Highlights
- [x] All linters passed
- [x] Well written HTML and CSS files
- [ ] Meaningful commit messages
- [ ] Correct use of Github flow
- [ ] Descriptive PR title and description.

## Required Changes ♻️
_Please check the comments under the review for suggested changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 19:16 UTC, Kamba56 commented on style.css
>  }
- [ ] Please stick to the design as much as possible. The body background color of your portfolio does not match that of the design template. Kindly fix that, please.
Your design![Screenshot 2022-08-20 194207](https://user-images.githubusercontent.com/94551484/185761938-afc63c2a-fcfc-4280-8781-9b79c8e52d56.png)
Design template![Screenshot 2022-08-20 194643](https://user-images.githubusercontent.com/94551484/185761943-1835ccec-6d13-495c-9c27-0993a0af6b94.png)

2022-08-20 19:16 UTC, Kamba56 commented on index.html
> -                    <a href="#"><img src="img/twitter.svg" alt="twitter" width="20" height="20"></a>
- [ ] Please note that you are to use an indentation of two spaces in all your document. This is a convention and also [best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). Kindly fix your indentation, please.

- [Optional] Consider adding a "Getting started" section in your readme file. This section should contain steps that one can take to get a local copy of your work. This will make your readme more professional.

2022-08-20 19:16 UTC, Kamba56 commented on index.html
>          <div class="headline-section">
- [Optional] Consider wrapping the headline section in a `<section>` element rather than a `<div>` this is best practice for HTML semantics.

2022-08-20 19:16 UTC, Kamba56 commented on style.css
> +}
- [ ] Please kindly make the hover and pressed interaction of the button to match that of the design template. You can use the `active` pseudo-class for the pressed effect
![Screenshot 2022-08-20 195928](https://user-images.githubusercontent.com/94551484/185762442-103814c6-461b-4022-ba8c-8899fa11f6a8.png)
.

2022-08-20 20:44 UTC, vvoo21 commented
Hi @Kamba56 
The changes have been done 😃.
Thank you!!!!

2022-08-20 21:02 UTC, vickymarz requested changes
Hi @vvoo21, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 21:02 UTC, victorokoroji commented on README.md
> +download and enjoy https://github.com/vvoo21/Portfolio
[OPTIONAL]

- [ ] The steps taken to get a local copy of the project as suggested by the previous reviewer should include:
       -  Clone the repo (write the name of the repo)
       -  Cd into the project (Write the name of the project directory)

2022-08-20 21:02 UTC, vickymarz commented on index.html
> +                </div>
- [ ] Good job adding the hover state as suggested by the previous reviewer 👍🏼 . Kindly make sure that the color of the button text also changes to white when you hover as shown in the Figma design.

Your Design 👇🏼 

![image](https://user-images.githubusercontent.com/63473584/185765876-0af59261-49d1-4d8a-97b7-3f7ab8c027dd.png)

Figma Design 👇🏼 

![image](https://user-images.githubusercontent.com/63473584/185765892-ec3275d5-84ab-4e73-a533-fdf16bffa959.png)

2022-08-20 22:43 UTC, vvoo21 commented
Hi @vickymarz , 
Thanks for the new review. The changes have been done. 😸.

2022-08-20 22:46 UTC, MeqdamAlqudah approved these changes
Hi @vvoo21 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 22:56 UTC, vvoo21 commented
Thanks @MeqdamAlqudah 
Happy coding!!! 🤝

2022-08-21 00:19 UTC, merged

2022-08-23 14:30 UTC, hopeforkoami reviewed
Hi @vvoo21,
you have done a great job
congratulations